# issueが非アクティブ状態からstaleになるまでの非アクティブな日数
daysUntilStale: 60
# staleなissueが閉じられるまでの日数
daysUntilClose: 7
# staleにさせないラベル
exemptLabels:
  - pinned
  - security
# staleとみなすLabel
staleLabel: wontfix
# Issueを閉じる際のコメント
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# コメントを投稿する (true) / 投稿しない (false)
closeComment: false
