name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/5 * * * *"
  
  workflow_dispatch:
    branches: [ master ]

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale this issue'
        stale-pr-message: 'Stale this pull request'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 0
        days-before-close: 0
